all:
  hosts:
    ubuntu-server:
      ansible_user: ubuntu
      ansible_host: 18.217.19.215
      ansible_ssh_private_key_file: ./ansible-servers
    centos-server:
      ansible_user: ec2-user
      ansible_host: 18.218.115.74
      ansible_ssh_private_key_file: ./ansible-servers
      ansible_python_interpreter: /usr/bin/python3

  children:
    web:
      hosts:
        ubuntu-server
    db:
      hosts:
        centos-server